- hosts: all
  name: Laravel unit test job for OpenStackID

  tasks:

    - include_role:
        name: setup-test-laravel-env

    - include_role:
        name: bindep

    - include_role:
        name: revoke-sudo

    - shell:
        cmd: |
          set -e
          set -x
          /usr/bin/php --version
          curl -s https://getcomposer.org/installer | /usr/bin/php
          /usr/bin/php composer.phar install --prefer-dist --ignore-platform-reqs
          /usr/bin/php artisan doctrine:clear:metadata:cache
          /usr/bin/php artisan doctrine:clear:query:cache
          /usr/bin/php artisan doctrine:clear:result:cache
          /usr/bin/php artisan doctrine:generate:proxies
          /usr/bin/php artisan view:clear
          /usr/bin/php artisan view:cache
          ./vendor/bin/phpunit
        chdir: '{{ zuul.project.src_dir }}'
