- hosts: all
  name: Tag tarball job for OpenStackID

  tasks:

    - include_role:
        name: setup-test-laravel-env

    - include_role:
        name: bindep

    - include_role:
        name: revoke-sudo

    - shell:
        cmd: |
          set -e
          set -x
          curl -s https://getcomposer.org/installer | /usr/bin/php
          /usr/bin/php composer.phar self-update 1.10.15
          /usr/bin/php composer.phar install --prefer-dist \
              --ignore-platform-reqs

          # copied from https://opendev.org/openstack/openstack-zuul-jobs/
          #   src/branch/master/roles/legacy-copy-jenkins-scripts/files/
          #   version-properties.sh
          # but there is probably a better solution for this
          SCM_TAG=$(git describe --abbrev=0 --tags) || true
          SCM_SHA=$(git rev-parse --short HEAD) || true
          COMMITS_SINCE_TAG=$(git describe \
              | awk '{split($0,a,"-"); print a[2]}') || true
          if [[ "${SCM_TAG}" == "" ]]; then
              SCM_TAG=$SCM_SHA
          fi
          if [[ "${COMMITS_SINCE_TAG}" == "" ]]; then
              PROJECT_VER=$SCM_TAG
          else
              PROJECT_VER="$SCM_TAG.$COMMITS_SINCE_TAG.$SCM_SHA"
          fi

          # Clone to dist
          rm -rf dist
          mkdir dist
          rsync -arv --exclude ".git*" --exclude tarballs --exclude dist . dist
          # Clean/create a tarball directory
          rm -rf tarballs
          mkdir -p tarballs
          # Create an archive tarball.
          tar -czf {{ zuul.project.short_name }}-$PROJECT_VER.tar.gz dist/
          cp {{ zuul.project.short_name }}-$PROJECT_VER.tar.gz \
              tarballs/{{ zuul.project.short_name }}-latest.tar.gz
          mv {{ zuul.project.short_name }}-$PROJECT_VER.tar.gz tarballs/
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
