- hosts: all
  tasks:

    - name: Ensure artifact transit directory exists
      file:
        path: '{{ zuul.executor.work_root }}/artifacts'
        state: directory
      delegate_to: localhost

    - name: Copy files from {{ zuul.project.src_dir }}/tarballs/ on node
      synchronize:
        src: '{{ zuul.project.src_dir }}/tarballs/'
        dest: '{{ zuul.executor.work_root }}/artifacts/'
        mode: pull
        verify_host: true
