# This is a basic workflow to help you get started with Actions

name: Nigthly Unit Tests Run

on:
  schedule:
    - cron:  '0 0 * * *'    # At the end of every day

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "unit-tests"
  unit-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: smarcet/openstackid_test:v1.0
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 'Run Unit Tests'
        run: cd / && ./tests.sh 2>&1 | tee /output.log
      - name: 'Upload Unit Test Output'
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: /output.log
          retention-days: 5
