# This is a basic workflow to help you get started with Actions

name: Unit Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "main" branch
  pull_request:
    types: [opened, reopened, edited,synchronize]
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "unit-tests"
  unit-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
        image: smarcet/openstackid_test:v1.0
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       - name: 'Run Unit Tests'
         run: cd / && ./tests.sh ${{ github.event.pull_request.head.sha }} 2>&1 | tee /output.log
       - name: 'Upload Unit Test Output'
         uses: actions/upload-artifact@v3
         with:
           name: output
           path: /output.log
           retention-days: 5
